/*
    list action for applications
*/
const Actions =  {
    USER_LOGIN : 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_UPDATE: 'USER_UPDATE',
    SWITCH_SALE_AUCTION: 'SWITCH_SALE_AUCTION',
    SET_CURRENT_INVENTORY_ID: 'SET_CURRENT_INVENTORY_ID',
    FAVOTITE_NFT_CALL_API_SERVER: 'FAVOTITE_NFT_CALL_API_SERVER',
    FAVOTITE_NFT_FORCE_UPDATE: 'FAVOTITE_NFT_FORCE_UPDATE',
}

export default Actions;